# Generated by Django 4.2.1 on 2025-02-12 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projectFlowApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFlowType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(db_index=True, max_length=255)),
                ('project_name_hinit', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('main_image', models.FileField(blank=True, null=True, upload_to='project_flow/ProjectFlowType/image/', validators=[projectFlowApp.models.validate_image])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFlowTypeExtraImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_flow_extra_image', models.FileField(upload_to='project_flow/ProjectFlowType/extra_images/', validators=[projectFlowApp.models.validate_image])),
                ('project_flow_extra_image_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowTypeImages_project_name_ProjectFlowType', to='projectFlowApp.projectflowtype')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFlowTypeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='project_flow/ProjectFlowType/attachment/', validators=[projectFlowApp.models.validate_file_or_image])),
                ('file_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowTypeAttachment_project_name_ProjectFlowType', to='projectFlowApp.projectflowtype')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_flow_status', models.CharField(choices=[('open', 'open'), ('wait_customer_action', 'wait_customer_action'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('canceled', 'canceled')], default='open', max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('project_created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProjectFlow_project_created_user_related_User', to=settings.AUTH_USER_MODEL)),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProjectFlow_project_name_related_ProjectFlowType', to='projectFlowApp.projectflowtype')),
                ('project_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProjectFlow_project_user_related_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
