# Generated by Django 4.2.1 on 2025-02-13 07:18

from django.db import migrations, models
import django.utils.timezone
import projectFlowApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0002_projectflownote_projectflownoteattachment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttype',
            old_name='project_name_hinit',
            new_name='project_name_hint',
        ),
        migrations.AddField(
            model_name='projectflowstep',
            name='step_description_ar',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectflowstep',
            name='step_name_ar',
            field=models.CharField(db_index=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttype',
            name='project_description_ar',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttype',
            name='project_name_ar',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttype',
            name='project_name_hint_ar',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steptemplate',
            name='step_description_ar',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steptemplate',
            name='step_name_ar',
            field=models.CharField(db_index=True, default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectflow',
            name='project_flow_status',
            field=models.CharField(choices=[('pending', 'pending'), ('wait_customer_action', 'wait_customer_action'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('canceled', 'canceled')], default='open', max_length=30),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='ProjectType/image/', validators=[projectFlowApp.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='projecttypeattachment',
            name='file_path',
            field=models.FileField(upload_to='ProjectType/attachment/', validators=[projectFlowApp.models.validate_file_or_image]),
        ),
        migrations.AlterField(
            model_name='projecttypeextraimages',
            name='project_flow_extra_image',
            field=models.FileField(upload_to='ProjectType/ProjectTypeExtraImages/', validators=[projectFlowApp.models.validate_image]),
        ),
    ]
