# Generated by Django 4.2.1 on 2025-02-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0003_rename_project_name_hinit_projecttype_project_name_hint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectflow',
            name='show_steps_to_client',
            field=models.BooleanField(default=True),
        ),
    ]
