# Generated by Django 4.2.1 on 2025-02-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0005_projecttype_project_slog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectflow',
            old_name='project_name',
            new_name='project_type',
        ),
        migrations.RenameField(
            model_name='projecttypeattachment',
            old_name='project_name',
            new_name='project_type',
        ),
        migrations.RenameField(
            model_name='projecttypeextraimages',
            old_name='project_name',
            new_name='project_type',
        ),
    ]
