# Generated by Django 4.2.1 on 2025-02-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0006_rename_project_name_projectflow_project_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectflow',
            name='details',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
