# Generated by Django 4.2.1 on 2025-02-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0007_projectflow_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectflow',
            name='project_flow_status',
            field=models.CharField(choices=[('pending', 'pending'), ('wait_customer_action', 'wait_customer_action'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('canceled', 'canceled')], default='pending', max_length=30),
        ),
    ]
