# Generated by Django 4.2.1 on 2025-02-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0008_alter_projectflow_project_flow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectflow',
            name='project_flow_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
