# Generated by Django 4.2.1 on 2025-02-14 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0009_projectflow_project_flow_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steptemplate',
            name='steps_template_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='StepsTemplate_steps_template_name_related_StepsTemplateName', to='projectFlowApp.stepstemplatename'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='steptemplatenote',
            name='step_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StepsTemplateNote_step_template_related_StepTemplate', to='projectFlowApp.steptemplate'),
        ),
    ]
