# Generated by Django 4.2.1 on 2025-02-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0010_alter_steptemplate_steps_template_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steptemplate',
            name='allowed_process_by',
            field=models.CharField(choices=[('any_staff', 'any_staff'), ('specific_staff_group', 'specific_staff_group'), ('client', 'client')], default='any_staff', max_length=30),
        ),
    ]
