# Generated by Django 4.2.1 on 2025-02-15 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0011_alter_steptemplate_allowed_process_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steptemplatenote',
            name='step_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='StepsTemplateNote_step_template_related_StepTemplate', to='projectFlowApp.steptemplate'),
            preserve_default=False,
        ),
    ]
