# Generated by Django 4.2.1 on 2025-02-15 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0013_rename_file_path_steptemplatenoteattachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steptemplatenoteattachment',
            name='step_template_note',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='StepTemplateNoteAttachment_step_template_note', to='projectFlowApp.steptemplatenote'),
            preserve_default=False,
        ),
    ]
