# Generated by Django 4.2.1 on 2025-02-16 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projectFlowApp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projectFlowApp', '0014_alter_steptemplatenoteattachment_step_template_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFlowSubStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('name_ar', models.CharField(db_index=True, max_length=255)),
                ('description_ar', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('wait_customer_action', 'wait_customer_action'), ('completed', 'completed'), ('canceled', 'canceled')], default='pending', max_length=30)),
                ('show_to_client', models.BooleanField(default=True)),
                ('allowed_process_by', models.CharField(choices=[('any_staff', 'any_staff'), ('specific_project_group', 'specific_project_group'), ('client', 'client')], default='any_staff', max_length=30)),
                ('sorted_weight', models.PositiveIntegerField(db_index=True, default=1000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('allowed_process_groups', models.ManyToManyField(blank=True, related_name='ProjectFlowSubStep_groups', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFlowSubStepNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('sub_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowSubStepNote_sub_step_related_ProjectFlowSubStep', to='projectFlowApp.projectflowsubstep')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProjectFlowSubStepNote_user_related_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='projectflownote',
            name='project_flow',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowNote_project_flow_related_ProjectFlow', to='projectFlowApp.projectflow'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectflowstep',
            name='allowed_process_by',
            field=models.CharField(choices=[('any_staff', 'any_staff'), ('specific_project_group', 'specific_project_group'), ('client', 'client')], default='any_staff', max_length=30),
        ),
        migrations.AlterField(
            model_name='projectflowstep',
            name='project_flow',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowStep_ProjectFlow_related_ProjectFlow', to='projectFlowApp.projectflow'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectflowstepnote',
            name='project_step',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowStepNote_project_step_related_ProjectFlowStep', to='projectFlowApp.projectflowstep'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectFlowSubStepNoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_flow/ProjectFlowSubStepNoteAttachment/', validators=[projectFlowApp.models.validate_file_or_image])),
                ('file_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('sub_step_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowSubStepNoteAttachment_sub_step_note_related_ProjectFlowSubStepNote', to='projectFlowApp.projectflowsubstepnote')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFlowSubStepAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_flow/ProjectFlowSubStepAttachment/', validators=[projectFlowApp.models.validate_file_or_image])),
                ('file_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('sub_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowSubStepAttachment_sub_step_related_ProjectFlowSubStep', to='projectFlowApp.projectflowsubstep')),
            ],
        ),
        migrations.AddField(
            model_name='projectflowsubstep',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowSubStep_step_related_ProjectFlowStep', to='projectFlowApp.projectflowstep'),
        ),
        migrations.AddField(
            model_name='projectflowsubstep',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProjectFlowSubStep_user_reloated_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectFlowStepAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_flow/ProjectFlowSubStepAttachment/', validators=[projectFlowApp.models.validate_file_or_image])),
                ('file_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowStepAttachment_step_related_ProjectFlowStep', to='projectFlowApp.projectflowstep')),
            ],
        ),
    ]
