# Generated by Django 4.2.1 on 2025-02-16 07:59

from django.db import migrations, models
import django.db.models.deletion
import projectFlowApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0015_projectflowsubstep_projectflowsubstepnote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectflownoteattachment',
            old_name='file_path',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='projectflowstepnoteattachment',
            old_name='file_path',
            new_name='file',
        ),
        migrations.CreateModel(
            name='ProjectFlowAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_flow/ProjectFlowAttachment/', validators=[projectFlowApp.models.validate_file_or_image])),
                ('file_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('project_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowAttachment_project_flow_related_ProjectFlow', to='projectFlowApp.projectflow')),
            ],
        ),
    ]
