# Generated by Django 4.2.1 on 2025-02-16 09:23

from django.db import migrations, models
import django.db.models.deletion
import projectFlowApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0016_rename_file_path_projectflownoteattachment_file_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StepsTemplateName',
            new_name='ProjectFlowTemplate',
        ),
        migrations.RemoveField(
            model_name='steptemplate',
            name='steps_template_name',
        ),
        migrations.AddField(
            model_name='steptemplate',
            name='project_flow_template',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='StepTemplate_project_flow_template_related_ProjectFlowTemplate', to='projectFlowApp.projectflowtemplate'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StepTemplateAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_flow/ProjectFlowNoteAttachment/', validators=[projectFlowApp.models.validate_file_or_image])),
                ('file_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('step_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowAttachment_step_template_related_StepTemplate', to='projectFlowApp.steptemplate')),
            ],
        ),
    ]
