# Generated by Django 4.2.1 on 2025-02-16 09:50

from django.db import migrations, models
import django.db.models.deletion
import projectFlowApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projectFlowApp', '0017_rename_stepstemplatename_projectflowtemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFlowTemplateNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('project_flow_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowTemplateNote_project_flow_template_releated_ProjectFlowTemplate', to='projectFlowApp.projectflowtemplate')),
            ],
        ),
        migrations.AlterField(
            model_name='steptemplateattachment',
            name='file',
            field=models.FileField(upload_to='project_flow/StepTemplateAttachment/', validators=[projectFlowApp.models.validate_file_or_image]),
        ),
        migrations.AlterField(
            model_name='steptemplateattachment',
            name='step_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StepTemplateAttachment_step_template_StepTemplate', to='projectFlowApp.steptemplate'),
        ),
        migrations.AlterField(
            model_name='steptemplatenoteattachment',
            name='step_template_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StepTemplateNoteAttachment_step_template_note_StepTemplateNote', to='projectFlowApp.steptemplatenote'),
        ),
        migrations.CreateModel(
            name='SubStepTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_step_name', models.CharField(db_index=True, max_length=255)),
                ('sub_step_description', models.TextField()),
                ('sub_step_name_ar', models.CharField(db_index=True, max_length=255)),
                ('sub_step_description_ar', models.TextField()),
                ('show_to_client', models.BooleanField(default=True)),
                ('allowed_process_by', models.CharField(choices=[('any_staff', 'any_staff'), ('specific_staff_group', 'specific_staff_group'), ('client', 'client')], default='any_staff', max_length=30)),
                ('sorted_weight', models.PositiveIntegerField(db_index=True, default=1000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('allowed_process_groups', models.ManyToManyField(blank=True, related_name='SubStepTemplate_groups', to='auth.group')),
                ('step_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubStepTemplate_step_template_StepTemplate', to='projectFlowApp.steptemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFlowTemplateNoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_flow/ProjectFlowTemplateNoteAttachment/', validators=[projectFlowApp.models.validate_file_or_image])),
                ('file_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('project_flow_template_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowTemplateNoteAttachment_project_flow_template_note_related_ProjectFlowTemplateNote', to='projectFlowApp.projectflowtemplatenote')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFlowTemplateAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_flow/ProjectFlowTemplateAttachment/', validators=[projectFlowApp.models.validate_file_or_image])),
                ('file_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('project_flow_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowTemplateAttachment_project_flow_template_related_ProjectFlowTemplate', to='projectFlowApp.projectflowtemplate')),
            ],
        ),
    ]
