# Generated by Django 4.2.1 on 2025-02-16 09:53

from django.db import migrations, models
import django.db.models.deletion
import projectFlowApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0018_projectflowtemplatenote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubStepTemplateAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_flow/SubStepTemplateAttachment/', validators=[projectFlowApp.models.validate_file_or_image])),
                ('file_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('step_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubStepTemplateAttachment_step_template_related_StepTemplate', to='projectFlowApp.steptemplate')),
            ],
        ),
    ]
