# Generated by Django 4.2.1 on 2025-02-16 09:57

from django.db import migrations, models
import django.db.models.deletion
import projectFlowApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0019_substeptemplateattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubStepTemplateNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('sub_step_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubStepTemplateNote_sub_step_template_related_SubStepTemplate', to='projectFlowApp.substeptemplate')),
            ],
        ),
        migrations.CreateModel(
            name='SubStepTemplateNoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_flow/StepTemplateNoteAttachment/', validators=[projectFlowApp.models.validate_file_or_image])),
                ('file_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('sub_step_template_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubStepTemplateNoteAttachment_sub_step_template_note_related_SubStepTemplateNote', to='projectFlowApp.substeptemplatenote')),
            ],
        ),
    ]
