# Generated by Django 4.2.1 on 2025-02-16 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0020_substeptemplatenote_substeptemplatenoteattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substeptemplate',
            name='step_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubStepTemplate_step_template_StepTemplate', to='projectFlowApp.steptemplate'),
        ),
        migrations.AlterField(
            model_name='substeptemplateattachment',
            name='step_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubStepTemplateAttachment_step_template_related_StepTemplate', to='projectFlowApp.steptemplate'),
        ),
        migrations.AlterField(
            model_name='substeptemplatenote',
            name='sub_step_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubStepTemplateNote_sub_step_template_related_SubStepTemplate', to='projectFlowApp.substeptemplate'),
        ),
        migrations.AlterField(
            model_name='substeptemplatenoteattachment',
            name='sub_step_template_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubStepTemplateNoteAttachment_sub_step_template_note_related_SubStepTemplateNote', to='projectFlowApp.substeptemplatenote'),
        ),
    ]
