# Generated by Django 4.2.1 on 2025-02-16 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0021_alter_substeptemplate_step_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectflowtemplateattachment',
            name='project_flow_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowTemplateAttachment_project_flow_template_related_ProjectFlowTemplate', to='projectFlowApp.projectflowtemplate'),
        ),
        migrations.AlterField(
            model_name='projectflowtemplatenote',
            name='project_flow_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowTemplateNote_project_flow_template_releated_ProjectFlowTemplate', to='projectFlowApp.projectflowtemplate'),
        ),
        migrations.AlterField(
            model_name='projectflowtemplatenoteattachment',
            name='project_flow_template_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowTemplateNoteAttachment_project_flow_template_note_related_ProjectFlowTemplateNote', to='projectFlowApp.projectflowtemplatenote'),
        ),
        migrations.AlterField(
            model_name='steptemplate',
            name='project_flow_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StepTemplate_project_flow_template_related_ProjectFlowTemplate', to='projectFlowApp.projectflowtemplate'),
        ),
        migrations.AlterField(
            model_name='steptemplateattachment',
            name='step_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StepTemplateAttachment_step_template_StepTemplate', to='projectFlowApp.steptemplate'),
        ),
        migrations.AlterField(
            model_name='steptemplatenote',
            name='step_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StepsTemplateNote_step_template_related_StepTemplate', to='projectFlowApp.steptemplate'),
        ),
        migrations.AlterField(
            model_name='steptemplatenoteattachment',
            name='step_template_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StepTemplateNoteAttachment_step_template_note_StepTemplateNote', to='projectFlowApp.steptemplatenote'),
        ),
    ]
