# Generated by Django 4.2.1 on 2025-02-16 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0022_alter_projectflowtemplateattachment_project_flow_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectflowsubstepnoteattachment',
            name='sub_step_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProjectFlowSubStepNoteAttachment_sub_step_note_related_ProjectFlowSubStepNote', to='projectFlowApp.projectflowsubstepnote'),
        ),
    ]
