# Generated by Django 4.2.1 on 2025-02-16 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0023_alter_projectflowsubstepnoteattachment_sub_step_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectflowsubstepnote',
            name='sub_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProjectFlowSubStepNote_sub_step_related_ProjectFlowSubStep', to='projectFlowApp.projectflowsubstep'),
        ),
    ]
