# Generated by Django 4.2.1 on 2025-02-18 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0027_alter_steptemplate_project_flow_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substeptemplateattachment',
            name='step_template',
        ),
        migrations.AddField(
            model_name='substeptemplateattachment',
            name='sub_step_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubStepTemplateAttachment_sub_step_template_StepTemplate', to='projectFlowApp.steptemplate'),
        ),
    ]
