# Generated by Django 4.2.1 on 2025-02-18 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0028_remove_substeptemplateattachment_step_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substeptemplateattachment',
            name='sub_step_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubStepTemplateAttachment_sub_step_template_SubStepTemplate', to='projectFlowApp.substeptemplate'),
        ),
    ]
