# Generated by Django 4.2.1 on 2025-02-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0031_alter_steptemplate_sorted_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='substeptemplate',
            options={'ordering': ['sorted_weight']},
        ),
        migrations.AlterField(
            model_name='substeptemplate',
            name='sorted_weight',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0),
        ),
    ]
