# Generated by Django 4.2.1 on 2025-02-20 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0033_projectflowtemplate_template_name_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substeptemplateattachment',
            name='sub_step_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubStepTemplateAttachment_sub_step_template_related_SubStepTemplate', to='projectFlowApp.substeptemplate'),
        ),
    ]
