# Generated by Django 4.2.1 on 2025-02-20 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0034_alter_substeptemplateattachment_sub_step_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttypeextraimages',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectTypeExtraImages_project_type_related_ProjectType', to='projectFlowApp.projecttype'),
        ),
    ]
