# Generated by Django 4.2.1 on 2025-02-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0035_alter_projecttypeextraimages_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectflowsubstepattachment',
            name='sub_step',
        ),
        migrations.RemoveField(
            model_name='projectflowsubstepnote',
            name='sub_step',
        ),
        migrations.RemoveField(
            model_name='projectflowsubstepnote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projectflowsubstepnoteattachment',
            name='sub_step_note',
        ),
        migrations.AddField(
            model_name='projectflow',
            name='test_field',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='ProjectFlowSubStep',
        ),
        migrations.DeleteModel(
            name='ProjectFlowSubStepAttachment',
        ),
        migrations.DeleteModel(
            name='ProjectFlowSubStepNote',
        ),
        migrations.DeleteModel(
            name='ProjectFlowSubStepNoteAttachment',
        ),
    ]
