# Generated by Django 4.2.1 on 2025-02-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0036_remove_projectflowsubstepattachment_sub_step_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectflow',
            old_name='test_field',
            new_name='project_type_name',
        ),
        migrations.AddField(
            model_name='projectflow',
            name='project_type_name_ar',
            field=models.CharField(default='', max_length=255),
        ),
    ]
