# Generated by Django 4.2.1 on 2025-02-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0038_alter_projectflow_project_type_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectflow',
            name='start_process_step_or_sub_step_strategy',
            field=models.CharField(choices=[('auto', 'auto'), ('manual', 'manual')], default='auto', max_length=30),
        ),
    ]
