# Generated by Django 4.2.1 on 2025-02-21 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectFlowApp', '0041_alter_projectflow_project_created_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectflow',
            name='project_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProjectFlow_project_user_related_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectflowattachment',
            name='project_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowAttachment_project_flow_related_ProjectFlow', to='projectFlowApp.projectflow'),
        ),
        migrations.AlterField(
            model_name='projectflownote',
            name='project_flow_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProjectFlowNote_project_flow_user_related_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectflowstep',
            name='project_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowStep_ProjectFlow_related_ProjectFlow', to='projectFlowApp.projectflow'),
        ),
        migrations.AlterField(
            model_name='projectflowstep',
            name='step_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProjectFlowStep_step_user_related_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectflowstepattachment',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowStepAttachment_step_related_ProjectFlowStep', to='projectFlowApp.projectflowstep'),
        ),
        migrations.AlterField(
            model_name='projectflowstepnote',
            name='project_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowStepNote_project_step_related_ProjectFlowStep', to='projectFlowApp.projectflowstep'),
        ),
        migrations.AlterField(
            model_name='projectflowstepnote',
            name='step_note_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProjectFlowStepNote_step_note_user_related_ProjectFlowStep', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectflowstepnoteattachment',
            name='project_flow_step_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowStepNoteAttachment_project_flow_step_note_related_ProjectFlowStepNote', to='projectFlowApp.projectflowstepnote'),
        ),
    ]
