# Generated by Django 4.2.1 on 2025-02-21 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projectFlowApp.models.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projectFlowApp', '0042_alter_projectflow_project_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFlowSubStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_step_name', models.CharField(db_index=True, max_length=255)),
                ('sub_step_description', models.TextField()),
                ('sub_step_name_ar', models.CharField(db_index=True, max_length=255)),
                ('sub_step_description_ar', models.TextField()),
                ('show_to_client', models.BooleanField(default=True)),
                ('allowed_process_by', models.CharField(choices=[('any_staff', 'any_staff'), ('specific_staff_group', 'specific_staff_group'), ('client', 'client')], default='any_staff', max_length=30)),
                ('sorted_weight', models.PositiveIntegerField(blank=True, db_index=True, default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('start_process_sub_step_strategy', models.CharField(choices=[('inherit_from_project_flow', 'inherit_from_project_flow'), ('auto', 'auto'), ('manual', 'manual')], default='inherit_from_project_flow', max_length=30)),
                ('allowed_process_groups', models.ManyToManyField(blank=True, related_name='ProjectFlowSubStep_groups', to='auth.group')),
            ],
            options={
                'ordering': ['sorted_weight'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFlowSubStepNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('sub_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowSubStepNote_sub_step_related_ProjectFlowSubStep', to='projectFlowApp.projectflowsubstep')),
                ('sub_step_note_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProjectFlowSubStepNote_sub_step_note_user_related_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='projectflowstep',
            options={'ordering': ['sorted_weight']},
        ),
        migrations.AlterField(
            model_name='projectflowstepattachment',
            name='file',
            field=models.FileField(upload_to='project_flow/ProjectFlowStepAttachment/', validators=[projectFlowApp.models.utils.validate_file_or_image]),
        ),
        migrations.CreateModel(
            name='ProjectFlowSubStepNoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_flow/ProjectFlowSubStepNoteAttachment/', validators=[projectFlowApp.models.utils.validate_file_or_image])),
                ('file_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('sub_step_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowSubStepNoteAttachment_sub_step_note_related_ProjectFlowSubStepNote', to='projectFlowApp.projectflowsubstepnote')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFlowSubStepAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_flow/ProjectFlowSubStepAttachment/', validators=[projectFlowApp.models.utils.validate_file_or_image])),
                ('file_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('sub_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowSubStepAttachment_sub_step_ProjectFlowSubStep', to='projectFlowApp.projectflowsubstep')),
            ],
        ),
        migrations.AddField(
            model_name='projectflowsubstep',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowSubStep_step_related_ProjectFlowStep', to='projectFlowApp.projectflowstep'),
        ),
        migrations.AddField(
            model_name='projectflowsubstep',
            name='sub_step_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProjectFlowSubStep_sub_step_user_related_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
