# Generated by Django 4.2.1 on 2025-02-21 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0043_projectflowsubstep_projectflowsubstepnote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectflow',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProjectFlow_project_type_related_ProjectType', to='projectFlowApp.projecttype'),
        ),
    ]
