# Generated by Django 4.2.1 on 2025-02-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0044_alter_projectflow_project_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectflownote',
            old_name='project_flow_note',
            new_name='note',
        ),
    ]
