# Generated by Django 4.2.1 on 2025-02-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0045_rename_project_flow_note_projectflownote_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectflownote',
            old_name='project_flow_user',
            new_name='created_user',
        ),
    ]
