# Generated by Django 4.2.1 on 2025-02-22 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectFlowApp', '0046_rename_project_flow_user_projectflownote_created_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectflownote',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProjectFlowNote_created_user_related_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
