# Generated by Django 4.2.1 on 2025-02-23 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectFlowApp', '0047_alter_projectflownote_created_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectflowstep',
            old_name='end_data_process',
            new_name='end_date_process',
        ),
        migrations.RenameField(
            model_name='projectflowstep',
            old_name='start_data_process',
            new_name='start_date_process',
        ),
        migrations.RemoveField(
            model_name='projectflowstep',
            name='step_user',
        ),
        migrations.AddField(
            model_name='projectflowstep',
            name='handler_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProjectFlowStep_handler_user_related_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectFlowStepStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('wait_customer_action', 'wait_customer_action'), ('completed', 'completed'), ('canceled', 'canceled')], max_length=30)),
                ('new_status', models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('wait_customer_action', 'wait_customer_action'), ('completed', 'completed'), ('canceled', 'canceled')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project_flow_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowStepStatusLog_project_flow_step_related_ProjectFlowStep', to='projectFlowApp.projectflowstep')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProjectFlowStepStatusLog_user_related_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
