# Generated by Django 4.2.1 on 2025-02-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0048_rename_end_data_process_projectflowstep_end_date_process_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectflowstep',
            name='sorted_weight',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
