# Generated by Django 4.2.1 on 2025-02-23 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectFlowApp', '0049_alter_projectflowstep_sorted_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectflowsubstep',
            name='sub_step_user',
        ),
        migrations.AddField(
            model_name='projectflow',
            name='show_steps_or_sub_steps_status_log_to_client',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectflowstep',
            name='show_status_log_to_client',
            field=models.CharField(choices=[('inherit_from_project_flow', 'inherit_from_project_flow'), ('yes', 'yes'), ('no', 'no')], default='inherit_from_project_flow', max_length=30),
        ),
        migrations.AddField(
            model_name='projectflowsubstep',
            name='handler_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProjectFlowSubStep_handler_user_related_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectflowsubstep',
            name='project_flow_sub_step_status',
            field=models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('wait_customer_action', 'wait_customer_action'), ('completed', 'completed'), ('canceled', 'canceled')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='projectflowsubstep',
            name='show_status_log_to_client',
            field=models.CharField(choices=[('inherit_from_project_flow', 'inherit_from_project_flow'), ('yes', 'yes'), ('no', 'no')], default='inherit_from_project_flow', max_length=30),
        ),
        migrations.CreateModel(
            name='ProjectFlowSubStepStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('wait_customer_action', 'wait_customer_action'), ('completed', 'completed'), ('canceled', 'canceled')], max_length=30)),
                ('new_status', models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('wait_customer_action', 'wait_customer_action'), ('completed', 'completed'), ('canceled', 'canceled')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project_flow_sub_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectFlowSubStepStatusLog_project_flow_sub_step_related_ProjectFlowSubStep', to='projectFlowApp.projectflowsubstep')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProjectFlowSubStepStatusLog_user_related_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
