# Generated by Django 4.2.1 on 2025-02-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0050_remove_projectflowsubstep_sub_step_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectflowsubstep',
            name='end_date_process',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectflowsubstep',
            name='start_date_process',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
