# Generated by Django 4.2.1 on 2025-02-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0051_projectflowsubstep_end_date_process_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectflowtemplate',
            name='show_steps_or_sub_steps_status_log_to_client',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='steptemplate',
            name='show_status_log_to_client',
            field=models.CharField(choices=[('inherit_from_project_flow_template', 'inherit_from_project_flow_template'), ('yes', 'yes'), ('no', 'no')], default='inherit_from_project_flow_template', max_length=128),
        ),
        migrations.AddField(
            model_name='substeptemplate',
            name='show_status_log_to_client',
            field=models.CharField(choices=[('inherit_from_project_flow_template', 'inherit_from_project_flow_template'), ('yes', 'yes'), ('no', 'no')], default='inherit_from_project_flow_template', max_length=128),
        ),
    ]
