# Generated by Django 4.2.1 on 2025-02-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0052_projectflowtemplate_show_steps_or_sub_steps_status_log_to_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='steptemplate',
            name='step_type',
            field=models.CharField(default='default_step_type', max_length=50),
        ),
        migrations.AddField(
            model_name='substeptemplate',
            name='step_type',
            field=models.CharField(default='default_step_type', max_length=50),
        ),
    ]
