# Generated by Django 4.2.1 on 2025-02-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0053_steptemplate_step_type_substeptemplate_step_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectflowstep',
            name='step_type',
            field=models.CharField(default='default_step_type', max_length=50),
        ),
        migrations.AddField(
            model_name='projectflowsubstep',
            name='step_type',
            field=models.CharField(default='default_step_type', max_length=50),
        ),
    ]
