# Generated by Django 4.2.1 on 2025-02-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0054_projectflowstep_step_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectflow',
            name='is_template_mounted',
            field=models.BooleanField(default=False),
        ),
    ]
