# Generated by Django 4.2.1 on 2025-02-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0055_projectflow_is_template_mounted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttypeattachment',
            old_name='file_path',
            new_name='file',
        ),
    ]
