# Generated by Django 4.2.1 on 2025-02-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0056_rename_file_path_projecttypeattachment_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttypeextraimages',
            old_name='project_flow_extra_image',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='projecttypeextraimages',
            old_name='project_flow_extra_image_name',
            new_name='file_name',
        ),
    ]
