# Generated by Django 4.2.1 on 2025-03-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0057_rename_project_flow_extra_image_projecttypeextraimages_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steptemplate',
            name='show_status_log_to_client',
            field=models.CharField(choices=[('inherit_from_project_flow', 'inherit_from_project_flow'), ('yes', 'yes'), ('no', 'no')], default='inherit_from_project_flow', max_length=128),
        ),
        migrations.AlterField(
            model_name='substeptemplate',
            name='show_status_log_to_client',
            field=models.CharField(choices=[('inherit_from_project_flow', 'inherit_from_project_flow'), ('yes', 'yes'), ('no', 'no')], default='inherit_from_project_flow', max_length=128),
        ),
    ]
