# Generated by Django 4.2.1 on 2025-03-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0058_alter_steptemplate_show_status_log_to_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectflowstepnote',
            name='note_type',
            field=models.CharField(blank=True, default='normal', max_length=255, null=True),
        ),
    ]
