# Generated by Django 4.2.1 on 2025-03-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0059_projectflowstepnote_note_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectflownote',
            name='note_type',
            field=models.CharField(blank=True, default='normal', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectflowsubstepnote',
            name='note_type',
            field=models.CharField(blank=True, default='normal', max_length=255, null=True),
        ),
    ]
