# Generated by Django 4.2.1 on 2025-03-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0060_projectflownote_note_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectflownote',
            name='note_type',
            field=models.CharField(blank=True, db_index=True, default='normal', max_length=255, null=True),
        ),
    ]
