# Generated by Django 4.2.1 on 2025-03-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0063_alter_projectflow_project_flow_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectflow',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='projectflownote',
            name='show_to_client',
            field=models.BooleanField(default=True),
        ),
    ]
