# Generated by Django 4.2.1 on 2025-03-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0065_alter_projectflownote_show_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
