# Generated by Django 4.2.1 on 2025-03-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0067_alter_projecttype_project_slog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttype',
            name='project_slog',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
