# Generated by Django 4.2.1 on 2025-03-16 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0068_alter_projecttype_project_slog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectflowtemplate',
            name='template_name_ar',
        ),
    ]
