# Generated by Django 4.2.1 on 2025-03-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0069_remove_projectflowtemplate_template_name_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectflowtemplate',
            name='manual_start_mode',
            field=models.CharField(choices=[('serialized ', 'serialized '), ('non-serialized', 'non-serialized')], default='serialized', max_length=30),
        ),
    ]
