# Generated by Django 4.2.1 on 2025-03-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0070_projectflowtemplate_manual_start_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectflowtemplate',
            name='auto_start_first_step',
            field=models.BooleanField(default=True),
        ),
    ]
