# Generated by Django 4.2.1 on 2025-03-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0071_projectflowtemplate_auto_start_first_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectflowtemplate',
            old_name='auto_start_first_step',
            new_name='auto_start_first_step_after_mount',
        ),
    ]
