# Generated by Django 4.2.1 on 2025-03-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0073_alter_projectflowtemplate_manual_start_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectflowtemplate',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='projectflow',
            name='auto_start_first_step_after_mount',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectflow',
            name='manual_start_mode',
            field=models.CharField(choices=[('serialized', 'serialized'), ('non-serialized', 'non-serialized')], default='serialized', max_length=30),
        ),
    ]
