# Generated by Django 4.2.1 on 2025-03-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0074_alter_projectflowtemplate_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectflow',
            old_name='auto_start_first_step_after_mount',
            new_name='auto_start_first_step_after_clone',
        ),
        migrations.RenameField(
            model_name='projectflow',
            old_name='is_template_mounted',
            new_name='is_template_cloned',
        ),
        migrations.RenameField(
            model_name='projectflowtemplate',
            old_name='auto_start_first_step_after_mount',
            new_name='auto_start_first_step_after_clone',
        ),
    ]
