# Generated by Django 4.2.1 on 2025-03-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0075_rename_auto_start_first_step_after_mount_projectflow_auto_start_first_step_after_clone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectflow',
            name='template_name_cloned_from',
            field=models.CharField(default='', max_length=255),
        ),
    ]
