# Generated by Django 4.2.1 on 2025-03-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0076_projectflow_template_name_cloned_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steptemplateattachment',
            name='step_template',
        ),
        migrations.RemoveField(
            model_name='substeptemplateattachment',
            name='sub_step_template',
        ),
        migrations.AlterField(
            model_name='projectflowstep',
            name='allowed_process_by',
            field=models.CharField(choices=[('any_staff', 'any_staff'), ('specific_staff_group', 'specific_staff_group'), ('client', 'client')], default='any_staff', max_length=30),
        ),
        migrations.DeleteModel(
            name='ProjectFlowTemplateAttachment',
        ),
        migrations.DeleteModel(
            name='StepTemplateAttachment',
        ),
        migrations.DeleteModel(
            name='SubStepTemplateAttachment',
        ),
    ]
