# Generated by Django 4.2.1 on 2025-04-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0077_remove_steptemplateattachment_step_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectflow',
            name='project_flow_status_when_canceled',
            field=models.CharField(choices=[('pending', 'pending'), ('wait_customer_action', 'wait_customer_action'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('canceled', 'canceled')], default='pending', max_length=30),
        ),
    ]
