# Generated by Django 4.2.1 on 2025-05-02 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectFlowApp', '0078_projectflow_project_flow_status_when_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='steptemplatenote',
            name='step_note_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProjectFlowTemplateStepNote_step_note_user_related_ProjectFlowStep', to=settings.AUTH_USER_MODEL),
        ),
    ]
