# Generated by Django 4.2.1 on 2025-05-02 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectFlowApp', '0079_steptemplatenote_step_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='substeptemplatenote',
            name='sub_step_note_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProjectFlowTemplatesubStepNote_step_note_user_related_ProjectFlowStep', to=settings.AUTH_USER_MODEL),
        ),
    ]
