# Generated by Django 4.2.1 on 2025-05-04 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0080_substeptemplatenote_sub_step_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='default_template_to_mount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProjectType_default_template_to_mount_ProjectFlowTemplate', to='projectFlowApp.projectflowtemplate'),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='is_auto_mount_template',
            field=models.BooleanField(default=False),
        ),
    ]
