# Generated by Django 4.2.1 on 2025-05-05 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0081_projecttype_default_template_to_mount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttype',
            old_name='is_auto_mount_template',
            new_name='is_auto_clone_template',
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='default_template_to_mount',
        ),
        migrations.AddField(
            model_name='projecttype',
            name='default_template_to_clone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProjectType_default_template_to_clone_ProjectFlowTemplate', to='projectFlowApp.projectflowtemplate'),
        ),
    ]
