# Generated by Django 4.2.1 on 2025-05-05 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0082_rename_is_auto_mount_template_projecttype_is_auto_clone_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('project_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_products', to='projectFlowApp.projectflow')),
            ],
        ),
    ]
