# Generated by Django 4.2.1 on 2025-05-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0083_installedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='installedproduct',
            name='note',
        ),
        migrations.RemoveField(
            model_name='installedproduct',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='installedproduct',
            name='project_flow',
        ),
        migrations.RemoveField(
            model_name='installedproduct',
            name='serial_number',
        ),
    ]
