# Generated by Django 4.2.1 on 2025-05-06 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0084_installedproducttype_remove_installedproduct_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedproduct',
            name='installed_product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installed_products_InstalledProductType', to='projectFlowApp.installedproducttype'),
        ),
        migrations.AddField(
            model_name='installedproduct',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='installedproduct',
            name='private_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='installedproduct',
            name='project_flow',
            field=models.ForeignKey(default=175, on_delete=django.db.models.deletion.CASCADE, related_name='installed_products_ProjectFlow', to='projectFlowApp.projectflow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installedproduct',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
