# Generated by Django 4.2.1 on 2025-05-06 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0085_installedproduct_installed_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedproduct',
            name='installed_product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_products_InstalledProductType', to='projectFlowApp.installedproducttype'),
        ),
    ]
