# Generated by Django 4.2.1 on 2025-05-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0087_installedproducttype_private_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedproducttype',
            name='product_name_ar',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
