# Generated by Django 4.2.1 on 2025-05-12 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectFlowApp', '0088_installedproducttype_product_name_ar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectflowsubstepattachment',
            name='sub_step',
        ),
        migrations.AddField(
            model_name='projectflowtemplatenote',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProjectFlowTemplateNote_created_user_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProjectFlowStepAttachment',
        ),
        migrations.DeleteModel(
            name='ProjectFlowSubStepAttachment',
        ),
    ]
