# Generated by Django 4.2.1 on 2025-05-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0089_remove_projectflowsubstepattachment_sub_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectflow',
            name='project_flow_status',
            field=models.CharField(choices=[('pending', 'pending'), ('wait_customer_action', 'wait_customer_action'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('canceled', 'canceled')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='projectflow',
            name='project_type_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectflow',
            name='project_type_name_ar',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
