# Generated by Django 4.2.1 on 2025-05-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0090_alter_projectflow_project_flow_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectflow',
            name='contact_phone_no',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='projectflow',
            name='project_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
