# Generated by Django 4.2.1 on 2025-05-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectFlowApp', '0091_projectflow_contact_phone_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectflow',
            name='created_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
