# Generated by Django 4.2.1 on 2024-11-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_title', models.TextField(blank=True, db_index=True, null=True, unique=True)),
                ('about_us_company_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('about_us_hint', models.TextField(blank=True, db_index=True, null=True, unique=True)),
                ('about_us_details', models.TextField(blank=True, db_index=True, null=True, unique=True)),
                ('about_us_title_ar', models.TextField(blank=True, db_index=True, null=True, unique=True)),
                ('about_us_company_name_ar', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('about_us_hint_ar', models.TextField(blank=True, db_index=True, null=True, unique=True)),
                ('about_us_details_ar', models.TextField(blank=True, db_index=True, null=True, unique=True)),
                ('about_us_created_date', models.DateTimeField(auto_now_add=True)),
                ('about_us_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompnayIfRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_if_right_title', models.CharField(db_index=True, max_length=255, null=True)),
                ('company_if_right_title_ar', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('company_if_right_created_date', models.DateTimeField(auto_now_add=True)),
                ('company_if_right_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureWhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feat_whyus_title', models.CharField(db_index=True, max_length=255, null=True)),
                ('feat_whyus_title_ar', models.CharField(db_index=True, max_length=255, null=True)),
                ('feat_whyus_created_date', models.DateTimeField(auto_now_add=True)),
                ('feat_whyus_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_title', models.CharField(db_index=True, max_length=255, null=True)),
                ('focus_detail', models.TextField(blank=True, db_index=True, null=True)),
                ('focus_image', models.ImageField(blank=True, null=True, upload_to='focus')),
                ('focus_title_ar', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('focus_detail_ar', models.TextField(blank=True, db_index=True, null=True)),
                ('focus_created_date', models.DateTimeField(auto_now_add=True)),
                ('focus_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_sec_title', models.TextField(blank=True, db_index=True, null=True, unique=True)),
                ('home_sec_details', models.TextField(blank=True, db_index=True, null=True, unique=True)),
                ('home_sec_image', models.ImageField(blank=True, null=True, upload_to='HomeSection')),
                ('home_sec_title_ar', models.TextField(blank=True, db_index=True, null=True, unique=True)),
                ('home_sec_details_ar', models.TextField(blank=True, db_index=True, null=True, unique=True)),
                ('home_sec_created_date', models.DateTimeField(auto_now_add=True)),
                ('home_sec_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_client_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('our_client_image', models.ImageField(blank=True, null=True, upload_to='clients')),
                ('our_client_created_date', models.DateTimeField(auto_now_add=True)),
                ('our_client_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurClientSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_client_sec_title', models.CharField(db_index=True, max_length=255, null=True)),
                ('our_client_sec_ar', models.CharField(db_index=True, max_length=255, null=True)),
                ('our_client_sec_created_date', models.DateTimeField(auto_now_add=True)),
                ('our_client_sec_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servic_sec_title', models.CharField(db_index=True, max_length=255, null=True)),
                ('servic_sec_sub_title', models.CharField(db_index=True, max_length=255, null=True)),
                ('servic_sec_hint', models.CharField(db_index=True, max_length=255, null=True)),
                ('servic_sec_title_ar', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('servic_sec_sub_title_ar', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('servic_sec_hint_ar', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('servic_sec_created_date', models.DateTimeField(auto_now_add=True)),
                ('servic_sec_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_vision_title', models.CharField(db_index=True, max_length=255, null=True)),
                ('our_vision_detail', models.TextField(blank=True, db_index=True, null=True)),
                ('our_vision_title_ar', models.CharField(db_index=True, max_length=255, null=True)),
                ('our_vision_detail_ar', models.TextField(blank=True, db_index=True, null=True)),
                ('our_vision_created_date', models.DateTimeField(auto_now_add=True)),
                ('our_vision_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('prod_name_hint', models.CharField(db_index=True, max_length=255, null=True)),
                ('prod_details_hint', models.TextField(blank=True, db_index=True, null=True)),
                ('prod_details', models.TextField(blank=True, db_index=True, null=True)),
                ('prod_image', models.ImageField(blank=True, null=True, upload_to='Product')),
                ('prod_name_ar', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('prod_name_hint_ar', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('prod_details_ar', models.TextField(blank=True, db_index=True, null=True)),
                ('prod_slog', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('prod_created_date', models.DateTimeField(auto_now_add=True)),
                ('prod_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_sec_title', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
                ('prd_sec_hint', models.CharField(db_index=True, max_length=255, null=True)),
                ('prd_sec_title_ar', models.CharField(db_index=True, max_length=255, null=True)),
                ('prd_sec_hint_ar', models.CharField(db_index=True, max_length=255, null=True)),
                ('prd_sec_created_date', models.DateTimeField(auto_now_add=True)),
                ('prd_sec_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('service_detail', models.TextField(blank=True, db_index=True, null=True)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service')),
                ('service_name_ar', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('service_detail_ar', models.TextField(blank=True, db_index=True, null=True)),
                ('service_created_date', models.DateTimeField(auto_now_add=True)),
                ('service_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_us_title', models.TextField(blank=True, db_index=True, null=True, unique=True)),
                ('why_us_image', models.ImageField(blank=True, null=True, upload_to='WhyUs')),
                ('why_us_details', models.TextField(blank=True, db_index=True, null=True, unique=True)),
                ('why_us_title_ar', models.TextField(blank=True, db_index=True, null=True, unique=True)),
                ('why_us_details_ar', models.TextField(blank=True, db_index=True, null=True, unique=True)),
                ('why_us_created_date', models.DateTimeField(auto_now_add=True)),
                ('why_us_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
