# Generated by Django 4.2.1 on 2024-12-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteusersApp', '0003_alter_product_prod_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_details',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_details_hint',
            field=models.TextField(db_index=True),
        ),
    ]
