# Generated by Django 4.2.1 on 2024-12-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteusersApp', '0004_alter_product_prod_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservicessection',
            name='servic_sec_hint',
            field=models.CharField(db_index=True, default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ourservicessection',
            name='servic_sec_hint_ar',
            field=models.CharField(db_index=True, default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ourservicessection',
            name='servic_sec_sub_title',
            field=models.CharField(db_index=True, default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ourservicessection',
            name='servic_sec_sub_title_ar',
            field=models.CharField(db_index=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ourservicessection',
            name='servic_sec_title',
            field=models.CharField(db_index=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ourservicessection',
            name='servic_sec_title_ar',
            field=models.CharField(db_index=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
