# Generated by Django 4.2.1 on 2024-12-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteusersApp', '0005_alter_ourservicessection_servic_sec_hint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_detail',
            field=models.TextField(blank=True, db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='service_detail_ar',
            field=models.TextField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(db_index=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name_ar',
            field=models.CharField(db_index=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
