# Generated by Django 4.2.1 on 2024-12-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteusersApp', '0008_alter_aboutus_about_us_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prod_details_hint',
        ),
    ]
