# Generated by Django 4.2.1 on 2024-12-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteusersApp', '0009_remove_product_prod_details_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_detail',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_detail_ar',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name_ar',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
