# Generated by Django 4.2.1 on 2024-12-12 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteusersApp', '0010_alter_service_service_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourclientsection',
            old_name='our_client_sec_ar',
            new_name='our_client_sec_title_ar',
        ),
    ]
