# Generated by Django 4.2.1 on 2024-12-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteusersApp', '0011_rename_our_client_sec_ar_ourclientsection_our_client_sec_title_ar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_content', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_us_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_us_phone', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
