# Generated by Django 4.2.1 on 2024-12-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteusersApp', '0013_socialmedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='facebook',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='socialmedia',
            old_name='instagram',
            new_name='instagram_url',
        ),
        migrations.RenameField(
            model_name='socialmedia',
            old_name='linkedIn',
            new_name='linkedIn_url',
        ),
        migrations.RenameField(
            model_name='socialmedia',
            old_name='twitter',
            new_name='twitter_url',
        ),
        migrations.RenameField(
            model_name='socialmedia',
            old_name='youtube',
            new_name='youtube_url',
        ),
    ]
