# Generated by Django 4.2.1 on 2025-01-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteusersApp', '0014_rename_facebook_socialmedia_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='about_us_content_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
