# Generated by Django 4.2.1 on 2025-03-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteusersApp', '0015_footer_about_us_content_ar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTypeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
                ('title_hinit', models.CharField(db_index=True, max_length=255, null=True)),
                ('title_ar', models.CharField(db_index=True, max_length=255, null=True)),
                ('title_hinit_ar', models.CharField(db_index=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
