# Generated by Django 4.2.1 on 2025-03-12 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteusersApp', '0016_projecttypesection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttypesection',
            old_name='title_hinit',
            new_name='title_hint',
        ),
        migrations.RenameField(
            model_name='projecttypesection',
            old_name='title_hinit_ar',
            new_name='title_hint_ar',
        ),
    ]
