# Generated by Django 4.2.1 on 2025-05-23 10:52

from django.db import migrations, models
import django.db.models.deletion
import siteusersApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteusersApp', '0018_productextraimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ProjectType/attachment/', validators=[siteusersApp.models.validate_file_or_image])),
                ('file_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductAttachment_product', to='siteusersApp.product')),
            ],
        ),
    ]
