# Generated by Django 4.2.1 on 2025-01-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersAuthApp', '0002_custompermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompermission',
            options={'default_permissions': (), 'managed': False, 'permissions': (('user_managment', 'User Managment'), ('site_managment', 'Site Managment'), ('ticket_change', 'Ticket Change'), ('ticket_delete', 'Ticket Delete'), ('ticket_attachment_add_after_submited', 'Ticket Attachment Add After Submited'), ('ticket_attachment_delete_after_submited', 'Ticket Attachment Delete After Submited'), ('ticket_reply_change', 'Ticket Reply Change'), ('ticket_reply_delete', 'Ticket Reply Delete'), ('ticket_reply_attachment_add_after_submited', 'Ticket Reply Attachment Add'), ('ticket_reply_attachment_delete_after_submited', 'Ticket Reply Attachment Delete'))},
        ),
    ]
