# Generated by Django 4.2.1 on 2025-01-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersAuthApp', '0004_alter_custompermission_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='PRF_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='PRF_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
