# Generated by Django 4.2.1 on 2025-05-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersAuthApp', '0010_alter_custompermission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompermission',
            options={'default_permissions': (), 'managed': False, 'permissions': (('user_managment', 'User Managment'), ('site_managment', 'Site Managment'), ('ticket_change', 'Ticket Change'), ('ticket_delete', 'Ticket Delete'), ('ticket_create_behalf_client', 'Ticket Create Behalf Client'), ('ticket_attachment_delete_after_submited', 'Ticket Attachment Delete After Submited'), ('ticket_reply_change', 'Ticket Reply Change'), ('ticket_reply_delete', 'Ticket Reply Delete'), ('ticket_reply_attachment_delete_after_submited', 'Ticket Reply Attachment Delete After Submited'), ('projectflow_create_behalf_client', 'ProjectFlow Create Behalf Client'), ('projectflow_note_delete', 'ProjectFlow Note Delete'), ('projectflow_step_note_delete', 'ProjectFlow Step Note Delete'), ('projectflow_delete', 'projectflow delete'), ('projectflow_step_delete', 'projectflow step delete'))},
        ),
    ]
