# Generated by Django 4.2.1 on 2025-05-22 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logSystemApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-id']},
        ),
    ]
