# Generated by Django 4.2.1 on 2025-05-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logSystemApp', '0002_alter_log_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='object_id',
            field=models.CharField(max_length=100),
        ),
    ]
