# Generated by Django 4.2.1 on 2025-07-07 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logSystemApp', '0003_alter_log_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action_type',
            field=models.CharField(choices=[('Add', 'Add'), ('Edit', 'Edit'), ('Delete', 'Delete'), ('Login', 'Login'), ('Logout', 'Logout')], max_length=6),
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(blank=True, max_length=15, null=True)),
                ('request_method', models.CharField(blank=True, max_length=15, null=True)),
                ('message', models.TextField()),
                ('traceback', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
