# Generated by Django 4.2.1 on 2025-07-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logSystemApp', '0004_alter_log_action_type_errorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='request_path',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
