# Generated by Django 4.2.1 on 2025-07-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logSystemApp', '0005_errorlog_request_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
