# Generated by Django 4.2.1 on 2024-11-29 07:51

from django.db import migrations, models
import django.db.models.deletion
import ticketSystemApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('department_name_ar', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_subject', models.CharField(db_index=True, max_length=50, verbose_name='ticket subject')),
                ('ticket_body', models.TextField(verbose_name='ticket body')),
                ('ticket_status', models.CharField(choices=[('open', 'open'), ('wait_customer_reply', 'wait_customer_reply'), ('replied_by_staff', 'replied_by_staff'), ('replied_by_customer', 'replied_by_customer'), ('solved', 'solved')], default='open', max_length=30)),
                ('ticket_slog', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('ticket_created_date', models.DateTimeField(auto_now_add=True)),
                ('ticket_updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TicketFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_file_ticket_file', models.FileField(upload_to='ticket/ticket_files/', validators=[ticketSystemApp.models.validate_file_or_image])),
                ('ticket_file_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('ticket_file_created_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketReplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_replay_body', models.TextField(verbose_name='ticket reply body')),
                ('ticket_replay_created_date', models.DateTimeField(auto_now_add=True)),
                ('ticket_replay_updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TicketReplyFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_replay_file', models.FileField(upload_to='ticket/ticket_replay_files/', validators=[ticketSystemApp.models.validate_file_or_image])),
                ('ticket_replay_file_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('ticket_replay_file_created_data', models.DateTimeField(auto_now_add=True)),
                ('ticket_replay_file_ticket_replay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_replay_files_ticket_replay_related_name', to='ticketSystemApp.ticketreplay')),
            ],
        ),
    ]
