# Generated by Django 4.2.1 on 2024-11-29 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticketSystemApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreplay',
            name='ticket_replay_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_replay_from_user_related_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketreplay',
            name='ticket_replay_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_replay_ticket_related_name', to='ticketSystemApp.ticket'),
        ),
        migrations.AddField(
            model_name='ticketfiles',
            name='ticket_file_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_files_ticket_related_name', to='ticketSystemApp.ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_user_closed_by_related_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_user_created_by_related_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_department_related_name', to='ticketSystemApp.department'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_user_related_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
