# Generated by Django 4.2.1 on 2024-12-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSystemApp', '0004_ticket_ticket_created_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreplay',
            name='ticket_replay_created_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
