# Generated by Django 4.2.1 on 2025-05-19 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketSystemApp', '0005_ticketreplay_ticket_replay_created_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_user_closed_by_related_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_user_created_by_related_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_user_related_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketfiles',
            name='ticket_file_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_files_ticket_related_name', to='ticketSystemApp.ticket'),
        ),
        migrations.AlterField(
            model_name='ticketreplay',
            name='ticket_replay_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_replay_from_user_related_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketreplay',
            name='ticket_replay_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_replay_ticket_related_name', to='ticketSystemApp.ticket'),
        ),
        migrations.AlterField(
            model_name='ticketreplyfiles',
            name='ticket_replay_file_ticket_replay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_replay_files_ticket_replay_related_name', to='ticketSystemApp.ticketreplay'),
        ),
    ]
