# Generated by Django 4.2.1 on 2025-05-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSystemApp', '0006_alter_ticket_ticket_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('open', 'open'), ('wait_customer_reply', 'wait_customer_reply'), ('replied_by_staff', 'replied_by_staff'), ('replied_by_customer', 'replied_by_customer'), ('solved', 'solved')], db_index=True, default='open', max_length=30),
        ),
    ]
